### ISSUE TITLE
install.sh does not recognize office being installed on RDP server

### ISSUE THREAD

**Issue by Delvien** [Fmstrat/winapps#22]
I do not use a local VM, but when I point the install.sh to a server, with patched regedit, it only shows i can run internet explorer through winapps.

I have office 365 installed on the RDP server.

`Installing...
  Checking for installed apps in RDP machine...
  Configuring Internet Explorer... Finished.
  Configuring Windows... Finished.
Installation complete.`

**Comment by shhkid** [comment]
Hi, seems like the the paths to your office applications aren't correct.
Just check where the executables in your VM are located.

**Comment by Fmstrat** [comment]
What version of Office are you running? The o365 paths are different and we have PR ongoing to add those.

**Comment by PascalDutch** [comment]
I have the same issude, I'm using Office365

**Comment by Fmstrat** [comment]
Fixed

**Comment by PascalDutch** [comment]
Still not working when I run install.sh after I pull. I also imported the register file again

**Comment by tdgroot** [comment]
@Fmstrat not fixed for me too, that's because my Office is installed at `C:\Program Files (x86)\Microsoft Office\root\Office16\WINWORD.exe`, not at `C:\Program Files\Microsoft Office\root\Office16\WINWORD.exe`.

**Comment by PascalDutch** [comment]
I think it depends on what install of Office you have, I use the 32 bit version (x86) so mine should also be in `C:\Program Files (x86)\...` but I think if you downloaded the 64 bit version it may be in `C:\Program Files\...`

**Comment by Fmstrat** [comment]
@PascalDutch @tdgroot Can you both supply me the full paths to your Office executables, along with which versions you have installed (PPT, Word, Excel, etc)? Once I have those it's an easy fix.

**Comment by Delvien** [comment]
New update works perfectly!

**Comment by PascalDutch** [comment]
> @PascalDutch @tdgroot Can you both supply me the full paths to your Office executables, along with which versions you have installed (PPT, Word, Excel, etc)? Once I have those it's an easy fix.

Directory:
`C:\Program Files (x86)\Microsoft Office\root\Office16`

Office365 version 2002.

If I manually edit the word `info` file it works like a charm.

**Comment by PascalDutch** [comment]
After I pulled it works perfectly now, thanks a lot!

**Comment by Fmstrat** [comment]
Yup, this commit should have done the trick: https://github.com/Fmstrat/winapps/commit/31153890b893215902a7b8c2f41d14ac1f96fd9c
